-- PostgreSQL schema for ROFlow.
-- Run this inside the target database, for example:
--   psql -d mydb -f config/sql/create_entities.sql

CREATE TABLE IF NOT EXISTS users
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    full_name     VARCHAR(150) NOT NULL,
    role          VARCHAR(20) NOT NULL CHECK (role IN ('advisor', 'technician')),
    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_users_role ON users (role);

CREATE TABLE IF NOT EXISTS customers
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name  VARCHAR(150) NOT NULL,
    phone      VARCHAR(20) NULL,
    email      VARCHAR(255) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_customers_phone ON customers (phone);
CREATE INDEX IF NOT EXISTS idx_customers_email ON customers (email);

CREATE TABLE IF NOT EXISTS vehicles
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER NOT NULL,
    vin         VARCHAR(17) NOT NULL UNIQUE,
    year        SMALLINT NOT NULL CHECK (year >= 1900),
    make        VARCHAR(50) NOT NULL,
    model       VARCHAR(50) NOT NULL,
    color       VARCHAR(40) NULL,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_vehicles_customer FOREIGN KEY (customer_id) REFERENCES customers (id)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_vehicles_customer ON vehicles (customer_id);

CREATE TABLE IF NOT EXISTS repair_orders
(
    id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ro_number               VARCHAR(20) NOT NULL UNIQUE,
    vehicle_id              INTEGER NOT NULL,
    advisor_id              INTEGER NOT NULL,
    technician_id           INTEGER NULL,
    mileage                 INTEGER NOT NULL CHECK (mileage >= 0),
    complaint               TEXT NOT NULL,
    status                  VARCHAR(32) NOT NULL DEFAULT 'intake'
        CHECK (status IN (
            'intake',
            'diagnosis',
            'inspected',
            'awaiting_approval',
            'repair',
            'ready_for_pickup',
            'closed'
        )),
    customer_token          VARCHAR(64) NULL UNIQUE,
    token_expires_at        TIMESTAMP NULL,
    inspection_submitted_at TIMESTAMP NULL,
    created_at              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    closed_at               TIMESTAMP NULL,
    deleted_at              TIMESTAMP NULL,
    CONSTRAINT fk_ro_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles (id)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_ro_advisor FOREIGN KEY (advisor_id) REFERENCES users (id)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_ro_technician FOREIGN KEY (technician_id) REFERENCES users (id)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_ro_status ON repair_orders (status);
CREATE INDEX IF NOT EXISTS idx_ro_advisor ON repair_orders (advisor_id);
CREATE INDEX IF NOT EXISTS idx_ro_technician ON repair_orders (technician_id);
CREATE INDEX IF NOT EXISTS idx_ro_vehicle ON repair_orders (vehicle_id);
CREATE INDEX IF NOT EXISTS idx_ro_token ON repair_orders (customer_token);
CREATE INDEX IF NOT EXISTS idx_ro_deleted ON repair_orders (deleted_at);

CREATE TABLE IF NOT EXISTS inspection_findings
(
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repair_order_id     INTEGER NOT NULL,
    title               VARCHAR(100) NOT NULL,
    description         TEXT NULL,
    photo_path          VARCHAR(255) NULL,
    estimated_cost      NUMERIC(8, 2) NOT NULL DEFAULT 0.00 CHECK (estimated_cost >= 0),
    approval_status     VARCHAR(20) NOT NULL DEFAULT 'pending'
        CHECK (approval_status IN ('pending', 'approved', 'declined')),
    customer_decided_at TIMESTAMP NULL,
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_findings_ro FOREIGN KEY (repair_order_id) REFERENCES repair_orders (id)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_findings_ro ON inspection_findings (repair_order_id);
CREATE INDEX IF NOT EXISTS idx_findings_approval ON inspection_findings (approval_status);
